"""
Email Service for sending HTML emails via SMTP.
Uses Python's built-in smtplib and email libraries.
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any, Optional
from config import settings
import logging
from datetime import datetime
import markdown

logger = logging.getLogger(__name__)

# Hardcoded recipient list
RECIPIENT_EMAILS = [
    "luckysolanki902@gmail.com",
]


class EmailService:
    """Service for sending formatted HTML emails."""
    
    def __init__(self):
        self.smtp_host = settings.smtp_host
        self.smtp_port = settings.smtp_port
        self.smtp_user = settings.smtp_user
        self.smtp_password = settings.smtp_password
        self.from_email = settings.email_from
        self.from_name = settings.email_from_name
        self.to_email = settings.email_to
    
    def _create_plain_text_fallback(self, article_data: Dict[str, Any]) -> str:
        """
        Create a plain text version of the email for clients that don't support HTML.
        
        Args:
            article_data: Article dictionary
            
        Returns:
            Plain text email body
        """
        topic_title = article_data["topic_title"]
        topic_rationale = article_data["topic_rationale"]
        notion_url = article_data.get("notion_url", settings.notion_parent_url)
        
        text = f"""
{topic_title}
{'=' * len(topic_title)}

{topic_rationale}

Read the full article in Notion: {notion_url}

This article includes:
- Executive overview and first-principles breakdown
- Mental models and frameworks
- Real-world applications for founders, engineers, and relationships
- Practical exercises and a 24-hour experiment
- Curated YouTube videos and research papers

---
Generated by AI Mentor
Sent to Lucky
        """.strip()
        
        return text
    
    def _render_html_email(self, article_data: Dict[str, Any], notion_url: str) -> str:
        """
        Convert markdown to email-safe HTML with YouTube and Resources sections.
        
        Args:
            article_data: Article dictionary from LLM
            notion_url: URL of the created Notion page
            
        Returns:
            HTML string
        """
        md_content = article_data.get("article_markdown", "")
        title = article_data.get("topic_title", "Daily Article")
        
        try:
            html_body = markdown.markdown(md_content, extensions=['extra'])
        except:
            html_body = f"<pre>{md_content}</pre>"
        
        # Build YouTube section
        youtube_html = ""
        youtube_videos = article_data.get("youtube", [])
        if youtube_videos:
            youtube_html = """
    <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">
    <h2 style="font-size: 22px; color: #1a1a1a;">📺 Recommended Videos</h2>
    <ul style="padding-left: 20px;">"""
            for video in youtube_videos:
                video_title = video.get("title", "Video")
                video_url = video.get("url", "")
                if video_url:
                    youtube_html += f'\n        <li style="margin-bottom: 8px;"><a href="{video_url}" style="color: #2b6cb0;">{video_title}</a></li>'
            youtube_html += "\n    </ul>"
        
        # Build Resources section
        resources_html = ""
        papers = article_data.get("papers", [])
        if papers:
            resources_html = """
    <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">
    <h2 style="font-size: 22px; color: #1a1a1a;">📚 Further Reading</h2>
    <ul style="padding-left: 20px;">"""
            for paper in papers:
                paper_title = paper.get("title", "Resource")
                paper_url = paper.get("url", "")
                if paper_url:
                    resources_html += f'\n        <li style="margin-bottom: 8px;"><a href="{paper_url}" style="color: #2b6cb0;">{paper_title}</a></li>'
                elif paper_title:
                    resources_html += f'\n        <li style="margin-bottom: 8px;">{paper_title}</li>'
            resources_html += "\n    </ul>"
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 20px; line-height: 1.7; color: #333;">
    <h1 style="font-size: 28px; color: #1a1a1a; margin-bottom: 30px;">{title}</h1>
    {html_body}
    {youtube_html}
    {resources_html}
    <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">
    <p style="font-size: 14px; color: #666;">
        <a href="{notion_url}" style="color: #2b6cb0;">Read in Notion</a> | 
        Dailicle - Your daily dose of wisdom
    </p>
</body>
</html>"""
    
    async def send_article_email(
        self, 
        article_data: Dict[str, Any],
        notion_url: str,
        to_emails: Optional[list] = None
    ) -> bool:
        """
        Send the article via email to multiple recipients.
        
        Args:
            article_data: Article dictionary from LLM
            notion_url: URL of the Notion page
            to_emails: Override recipient emails (optional)
            
        Returns:
            True if sent successfully to all, False otherwise
        """
        recipients = to_emails or RECIPIENT_EMAILS
        subject = article_data.get("email_subject", f"Dailycle: {article_data['topic_title']}")
        
        logger.info(f"Preparing to send email: {subject} to {len(recipients)} recipients")
        
        # Add notion_url to article_data for template
        article_data["notion_url"] = notion_url
        
        # Create plain text and HTML parts once
        plain_text = self._create_plain_text_fallback(article_data)
        html_content = self._render_html_email(article_data, notion_url)
        
        all_sent = True
        
        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                
                for to_email in recipients:
                    try:
                        # Create message for each recipient
                        msg = MIMEMultipart('alternative')
                        msg['Subject'] = subject
                        msg['From'] = f"{self.from_name} <{self.from_email}>"
                        msg['To'] = to_email
                        msg['Reply-To'] = self.from_email
                        
                        part1 = MIMEText(plain_text, 'plain')
                        part2 = MIMEText(html_content, 'html')
                        
                        msg.attach(part1)
                        msg.attach(part2)
                        
                        server.send_message(msg)
                        logger.info(f"✓ Email sent to {to_email}")
                    except Exception as e:
                        logger.error(f"✗ Failed to send to {to_email}: {e}")
                        all_sent = False
            
            logger.info(f"Email sending completed. Success: {all_sent}")
            return all_sent
            
        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            logger.error("Check your email credentials and app password")
            return False
        except smtplib.SMTPException as e:
            logger.error(f"SMTP error occurred: {e}")
            return False
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False
    
    async def send_test_email(self, to_email: Optional[str] = None) -> bool:
        """
        Send a test email to verify configuration.
        
        Args:
            to_email: Recipient email address
            
        Returns:
            True if sent successfully
        """
        to_email = to_email or self.to_email
        subject = "Dailicle Test Email"
        
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"{self.from_name} <{self.from_email}>"
        msg['To'] = to_email
        
        plain_text = """
This is a test email from Dailicle.

If you received this, your email configuration is working correctly!

The system is ready to send daily article emails.
        """.strip()
        
        html_content = """
<!doctype html>
<html>
<body style="font-family: Arial, sans-serif; padding: 20px;">
    <h2 style="color: #2b6cb0;">✅ Dailicle Test Email</h2>
    <p>If you received this, your email configuration is working correctly!</p>
    <p>The system is ready to send daily article emails.</p>
</body>
</html>
        """.strip()
        
        part1 = MIMEText(plain_text, 'plain')
        part2 = MIMEText(html_content, 'html')
        
        msg.attach(part1)
        msg.attach(part2)
        
        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            
            logger.info(f"Test email sent successfully to {to_email}")
            return True
        except Exception as e:
            logger.error(f"Failed to send test email: {e}")
            return False


# Global instance
email_service = EmailService()
